name: "Bug report"
description: Bug report
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report, please **confirm that your issue is not a duplicate issue and not because of your operation or version issues**
        感谢您花时间填写此错误报告，请**务必确认您的issue不是重复的且不是因为您的操作或版本问题**

  - type: checkboxes
    attributes:
      label: Please make sure of the following things
      description: |
        You must check all the following, otherwise your issue may be closed directly. Or you can go to the [discussions](https://github.com/eric-jxl/go/discussions)
        您必须勾选以下所有内容，否则您的issue可能会被直接关闭。或者您可以去[讨论区](https://github.com/eric-jxl/go/discussions)
      options:
        - label: |
            I have read the documentation.
            我已经阅读了文档。
        - label: |
            I'm sure there are no duplicate issues or discussions.
            我确定没有重复的issue或讨论。
     
        - label: |
            I'm sure this issue is not fixed in the latest version.
            我确定这个问题在最新版本中没有被修复。



  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug / 问题描述
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction / 复现链接
      description: |
        Please provide a link to a repo that can reproduce the problem you ran into. Please be aware that your issue may be closed directly if you don't provide it.
        请提供能复现此问题的链接，请知悉如果不提供它你的issue可能会被直接关闭。
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / 日志
      description: |
        Please copy and paste any relevant log output.
        请复制粘贴错误日志，或者截图
