name: build-go-binary

on:
  release:
    types: [ created ]


permissions:
  contents: write
  packages: write

jobs:
  build-go-binary:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [ linux, windows, darwin ] # 需要打包的系统
        goarch: [ amd64, arm64 ] # 需要打包的架构
        exclude: # 排除某些平台和架构
          - goarch: arm64
            goos: windows
    steps:
      - uses: actions/checkout@v4
      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: 1.23         # 可以指定编译使用的 Golang 版本
          binary_name: "amap"     # 可以指定二进制文件的名称
          project_path: "./weather"
          # build_flags  Additional arguments to pass the go build command.
          # build_command	T he actual command to build binary, typically go build. You may want to use other command wrapper, e.g., packr2, example build_command: 'packr2 build'.
          ldflags: "-s -w"
          pre_command: "export AMAP_KEY=${{ secrets.AMAP_KEY}}"
          # extra_files: README.md   # 需要包含的额外文件
          executable_compression: upx -v
          md5sum: false
          
